"""Update Role

Revision ID: 5e25706ad3d8
Revises: 1f7f340270da
Create Date: 2024-09-05 18:32:18.108863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e25706ad3d8'
down_revision: Union[str, None] = '1f7f340270da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    # ### end Alembic commands ###
